/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aurora: typeof import('./src/components/backgrounds/Aurora.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CaseInputArea: typeof import('./src/components/CaseInputArea.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CiteTag: typeof import('./src/components/CiteTag.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LeftSidebar: typeof import('./src/components/LeftSidebar.vue')['default']
    MegaMenu: typeof import('primevue/megamenu')['default']
    Menu: typeof import('primevue/menu')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
